name = "Normal Survival Guns"
author = "mcgen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c861624f33ae37cc1e2d3b91ebc59cc170ae875b0fa826ccaeb7aa76e46ff901"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
