name = "Lucky Blocks"
author = "Jon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bb59b74072942ff5410e78c67c641fc125a06bfe29e7f2f0f47eac8a5106f96"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
