name = "Lucky Blocks"
author = "Jon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba475ca17f8664ec7df00641c7609016fca8cb99336b31afe1995df998998ae2"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
