name = "Lucky Blocks"
author = "Jon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d44d78bde6666ef488997829e18e5963a2e3c8f655644ed0c5c759657562db17"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
