name = "Sandy Gunslinger"
author = "mcpy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea9e4cfd7d70f78121e791c7237dbc1d4ea9d6a4249e1b63af5780443f0f096d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
