name = "Superflat Mob Arena"
author = "mcgen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcb5a90a992b1286ddee9caf4090a263f607bc5c20656200caeb793bc72529b1"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
