name = "Gunslinger Realm"
author = "mcgen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fa901a86d8254be0c37254e16348f7003db3e178253a69b2dd691bcb9ef525b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
