name = "Lucky Blocks"
author = "Jon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb147c773285a6c89147165a7057b53878ab9d6c8e55f56c3091fac07a5e2ce4"

[versions]
fabric = "0.19.3"
minecraft = "1.21.5"
