name = "Normal Survival"
author = "Jon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54ecd6f6481a881d398e4700623f94005c9e1e5daa74e27eeb2f9b850a0f54bb"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
