name = "Normal Survival"
author = "Jon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09775c013c6c0872918b0265d3bb88ccb87624dc696947a8c4d625a225dc470f"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
