name = "Normal Survival"
author = "Jon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edc783003e51c82f8189228859aaea2375e591f1b35e5b3d0270d9eb89b58aea"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
