name = "Snowy Igloo Realm"
author = "mcgen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dec05cfed32badb77df8e92813693cdb6689ba856d9af1fa2fb32f97d3461333"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
