name = "Better Build"
author = "Jon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ac74a70d1bda27e25a6c76b9600fa479539f1dcd36012fcefb1ea60b24e18b9"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
