name = "Friends Lobby"
author = "Jon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87ec8a6c0730a356705ab140c9ee3a031f7f83c5a162403935075775d329aded"

[versions]
fabric = "0.19.3"
minecraft = "26.1.2"
