@echo off
REM GENERATED by tools\mc-publish.ps1 - do not edit by hand.
REM Same installer as the one-liner, for anyone who would rather double-click.
powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://play.datakiin.com/install.ps1 | iex"
echo.
pause
