# Normal Survival installer - GENERATED by tools\mc-publish.ps1. Do not edit by hand.
# Regenerate with: tools\mc-publish.ps1 normal-survival -Push
#
#   irm https://jongracias.github.io/MCServers/install.ps1 | iex
#
$Display   = 'Normal Survival'
$McVersion = '26.1.2'
$Fabric    = '0.19.3'
$PackUrl   = 'https://raw.githubusercontent.com/JonGracias/MCServers/master/normal-survival/pack.toml'
$JoinAddr  = 'survival.datakiin.com:25569'
$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$Bootstrap = 'https://github.com/packwiz/packwiz-installer-bootstrap/releases/latest/download/packwiz-installer-bootstrap.jar'

function Step($m) { Write-Host "  $m" -ForegroundColor Gray }
Write-Host ''
Write-Host "Installing $Display" -ForegroundColor Green

# 1. Prism Launcher
$prism = "$env:LOCALAPPDATA\Programs\PrismLauncher\prismlauncher.exe"
if (Test-Path $prism) {
    Step 'Prism Launcher: already installed'
} else {
    Step 'Prism Launcher: installing (winget)...'
    winget install PrismLauncher.PrismLauncher --silent --accept-package-agreements --accept-source-agreements
    if (-not (Test-Path $prism)) {
        Write-Host 'Prism did not install. Get it from https://prismlauncher.org and re-run this.' -ForegroundColor Red
        return
    }
}

# 2. The tile. Idempotent on purpose: an existing instance keeps its options.txt, saves,
#    screenshots and ReplayMod recordings - only the two config files are rewritten, so
#    re-running this repairs a broken tile instead of costing you your settings.
$inst  = Join-Path $env:APPDATA "PrismLauncher\instances\$Display"
$mine  = Join-Path $inst '.minecraft'
$fresh = -not (Test-Path (Join-Path $inst 'instance.cfg'))
New-Item -ItemType Directory -Force $mine | Out-Null

# Built by joining lines rather than with here-strings: this file is itself generated, and
# nested here-strings are what broke the first attempt at generating it.
$mmc = @(
    '{',
    '    "components": [',
    ('        { "important": true, "uid": "net.minecraft", "version": "' + $McVersion + '" },'),
    ('        { "uid": "net.fabricmc.fabric-loader", "version": "' + $Fabric + '" }'),
    '    ],',
    '    "formatVersion": 1',
    '}'
) -join "`r`n"
Set-Content (Join-Path $inst 'mmc-pack.json') $mmc -Encoding ASCII

# NO quotes in PreLaunchCommand - Prism's INI parser mangles them. $INST_JAVA is Prism's own
# variable, expanded by Prism at launch, so it must survive into the file un-expanded.
$cfg = @(
    '[General]',
    'ConfigVersion=1.2',
    'InstanceType=OneSix',
    'iconKey=default',
    ('name=' + $Display),
    'OverrideCommands=true',
    ('PreLaunchCommand=$INST_JAVA -jar packwiz-installer-bootstrap.jar ' + $PackUrl),
    'JoinServerOnLaunch=true',
    ('JoinServerOnLaunchAddress=' + $JoinAddr)
) -join "`r`n"
Set-Content (Join-Path $inst 'instance.cfg') $cfg -Encoding ASCII
Step $(if ($fresh) { "Instance created: $inst" } else { "Instance repaired (settings and saves kept): $inst" })

# 3. The bootstrap jar - this is what downloads the mods, every launch, from the pack URL.
$jar = Join-Path $mine 'packwiz-installer-bootstrap.jar'
if (-not (Test-Path $jar)) {
    Step 'Downloading packwiz installer...'
    Invoke-WebRequest $Bootstrap -OutFile $jar -UseBasicParsing
}

Write-Host ''
Write-Host 'Done.' -ForegroundColor Green
Write-Host "  Open Prism, sign in to your Microsoft account, and press Play on $Display." -ForegroundColor Gray
Write-Host '  The first launch downloads the mods and connects you automatically.' -ForegroundColor Gray
Write-Host ''
# Read-Host throws outright in a non-interactive host (piped, scheduled, CI). The install is
# already complete by this point, so a failure here must not read as a failed install.
$ans = 'n'
if ([Environment]::UserInteractive) {
    try { $ans = Read-Host 'Open Prism now? [Y/n]' } catch { $ans = 'n' }
}
if ($ans -eq '' -or $ans -match '^[Yy]') { Start-Process $prism }
