name = "Superflat"
author = "mcgen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaa4ba628ecd882944c6b74bca10f6aa7f73c24dfa059dba85959104091cf0f8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
