name = "Superflat"
author = "mcgen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc9532f5bee717cb7acd47b11e7974283a0818913feefb83a8aa66c27a7a7462"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
