name = "Superflat"
author = "mcgen"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57c0998141b68385eed5c5e30641245ce19bf23e0dff8af11eb16a5bf3e0f3e3"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
